# Generated by Django 4.2 on 2023-05-05 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_admin_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
